### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by ageorgios** [nickw444/sonoff-fw#1]
Hello, 
Is this repo a firmware for esp8266 for sonoff basic relay with homekit support?

Thank you.

**Comment by nickw444** [comment]
Heya, i'm in the process of moving across to a different mono-repo setup for all this automation stuff.

I haven't yet added my sonoff-relay firmware to the new repo, but there is now a sonoff TH-10/TH-16 firmware available over there. I plan on adding the relay firmware within a week.

Feel free to check it out: https://github.com/nickw444/homekit and re-create this issue over there if things are still unclear
